name: Flakiness User-Flow Cron - Navigation Performnace

on: push

jobs:
  navigation-performance:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v2

      - name: NPM CI
        run: npm ci

      - name: Build
        run: npm run build

      - name: User Flow Audit
        run: npx user-flow --ufPath="./user-flows/navigation-performance.uf.ts"  --url="http://localhost:4173/" --serveCommand="npm run serve" --awaitServeStdout="4173"

      - name: Compile & CleanUp
        id: compiler
        run: node scripts/compile-and-cleanup.js navigation-performance

      - uses: EndBug/add-and-commit@v7
        with:
          author_name: github-bot
          author_email: opensource@push-based.io
          message: 'Persist Updated Compiled Results'
          add: '*'
