name: user-flow-ci
on:
  pull_request:
jobs:
  user-flow:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v2

      - name: NPM CI
        run: npm ci

      - name: Build
        run: npm run build

      - name: User Flow Audit
        run: npx user-flow

      - name: Compile & CleanUp
        id: compiler
        run: node scripts/compile-and-cleanup.js

#      - uses: EndBug/add-and-commit@v9
#        with:
#          author_name: Flakiness Tester Bot
#          message: 'audit: Test user-flow flakiness in GH with localhost'
