name: user-flow-ci
on:
  pull_request:
jobs:
  user-flow:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v2

      - name: NPM CI
        run: npm ci

      - name: Build
        run: npm run build

      - name: User Flow Audit
        run: npx user-flow

      - name: Compile & CleanUp
        run: node scripts/compile-and-cleanup.js
