name: user-flow-ci
on:
  pull_request:
jobs:
  user-flow:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v2

      - name: NPM CI
        run: npm ci

      - name: Build
        run: npm run build

      - name: User Flow Audit
        run: npx

      - name: Executing user-flow CLI
        uses: push-based/user-flow-gh-action@v0.0.0-alpha.24
